on:
  pull_request_review:
    types: [submitted]
    branches: ['master','dev']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # extract branch name on pull request
      - name: Print branch name
        if: github.event.review.state == 'approved'
        run: |
          echo "Approve ✅  ${{ github.event.pull_request.head.ref }}"