name: Jira pull request validation

on:
  pull_request_review:
    types: [submitted]
    branches: ['master','dev']

jobs:
  jira_validation:

    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v2        
        
      - name: Node modules install
        if: github.event.review.state == 'approved'
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
        run: npm install

      - name: Run script
        if: github.event.review.state == 'approved'
        run: node jiraValidation.js
        env: 
          TICKET_ID: ${{ github.event.pull_request.head.ref }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}