name: Jira validation

on:
  pull_request_review:
    types: [submitted]
    branches:
      - 'WLD-*'
      - '!develop'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check if is approved PR
        if: github.event.review.state != 'approved'
        run: exit 1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules2-

      - run: yarn
        if: |
          steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Run script
        run: yarn jira:validation
        env:
          TICKET_ID: ${{ github.event.pull_request.head.ref }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
          JIRA_API_BASE_URL: ${{ secrets.JIRA_API_BASE_URL }}
